# Generated by Django 5.1.1 on 2024-09-04 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('model_no', models.CharField(max_length=255)),
                ('copy', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('per_copy_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mob', models.CharField(max_length=10)),
                ('franchise_name', models.CharField(blank=True, max_length=255, null=True)),
                ('advance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
